# Generated by Django 3.1.1 on 2021-10-21 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upravitel', '0002_upravitel_zgrada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upravitel',
            name='Zgrada',
        ),
    ]
